openapi: 3.0.1
info:
  title: Odoo Dooz Car Parts Integration API
  description: API for accessing Inventory Products data from Odoo
  version: 1.0.0
servers:
  - url: https://hamiltontech-jopart-stage02-24870574.dev.odoo.com/
    description: staging server
    
tags:
  - name: Products
    description: Products related to cars

paths:
  /api/v1/cars:
    get:
      tags: [Products]
      summary: Get detailed car model information
      description: Returns comprehensive details about all car models
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  count:
                    type: integer
                    example: 500
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CarDetails'

  api/v1/categories:
    get:
      tags: [Products]
      summary: Get list of all car product categories
      description: Returns comprehensive list about all car product categories
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  count:
                    type: integer
                    example: 11
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'

  api/v1/subcategories:
    get:
      tags: [Products]
      summary: Get list of all car product subcategories
      description: Returns comprehensive list about all car product subcategories
      security:
        - bearerAuth: []
      parameters:
        - name: category_id
          in: query
          description: ID of the category you want to see the subcategories of
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  count:
                    type: integer
                    example: 8
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Subcategory'

  api/v1/products:
    get:
      tags: [Products]
      summary: Get list of all car product subcategories
      description: Returns comprehensive list about all car product subcategories
      security:
        - bearerAuth: []
      parameters:
        - name: ssn_number
          in: query
          description: SSN of the car model you want to see the products of
          required: true
          schema:
            type: integer
        - name: category_id
          in: query
          description: ID of the category you want to filter products by
          required: false
          schema:
            type: integer
        - name: subcategory_id
          in: query
          description: ID of the subcategories you want to filter products by
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  count:
                    type: integer
                    example: 8
                  car_name:
                    type: string
                    example: MERCEDES-BENZ E 200 CGI (W212) 2009 - 2015
                  car_ssn_number:
                    type: string
                    example: 222
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Available authorizations - Bearer token
      
  schemas:
    CarDetails:
      type: object
      properties:
        id:
          type: integer
          example: 2499
        name:
          type: string
          example: CHEVROLET Spark (China) 2003 - 2009
        year_id:
          type: object
          properties:
            id:
              type: integer
              example: 100
            name:
              type: string
              example: 2003
        end_year_id:
          type: object
          properties:
            id:
              type: integer
              example: 106
            name:
              type: string
              example: 2009
        mmodel_id:
          type: object
          properties:
            id:
              type: integer
              example: 3187
            name:
              type: string
              example: Spark (China)
        type_id:
          type: object
          properties:
            id:
              type: integer
              example: 248
            name:
              type: string
              example: 800 cc
        make_id:
          type: object
          properties:
            id:
              type: integer
              example: 102
            name:
              type: string
              example: CHEVROLET
        model_group:
          type: object
          properties:
            id:
              type: integer
              example: 1697
            name:
              type: string
              example: Spark (China)
        engine_code:
          type: string
          example: F8CV|F8CVC
        no_cylinder:
          type: integer
          example:  3
        body_style:
          type: string
          example:  hatchback
        fuel_type:
          type: string
          example:  gasoline
        drive_type:
          type: string
          example:  front_wheel
        oil_capacity:
          type: float
          example: 3.0
        ssn_number:
          type: integer
          example: 13109
    
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 95
        name:
          type: string
          example: Accessories
        sequence:
          type: integer
          example: 10000
        product_count:
          type: integer
          example: 0
    
    Subcategory:
      type: object
      properties:
        id:
          type: integer
          example: 214
        name:
          type: string
          example: Universal Accessories
        sequence:
          type: integer
          example: 10097
        parent_id:
          type: object
          properties:
            id:
              type: integer
              example: 95
            name:
              type: string
              example: Accessories
        product_count:
          type: integer
          example: 0
    
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 14003
        name:
          type: string
          example: [BAF/PBEB53] Peak Antifreeze Electric Vehicles (Blue) - 3.78 Liter
        default_code:
          type: string
          example: BAF/PBEB53
        barcode:
          type: boolean
          example: false
        list_price:
          type: float
          example: 17.0
        currency:
          type: string
          example: JOD
        main_image:
          type: string
          example: https://hamiltontech-jopart-stage02-24870574.dev.odoo.com/web/image/product.product/14003/image_1920
        extra_images:
          type: array
          items:
            type: string
        about_product:
          type: string
          example: Electric Vehicle Blue Antifreeze Coolant \nA high-performance, phosphate- and silicate-free blue coolant specially formulated for electric and hybrid vehicles. It offers excellent thermal stability, corrosion protection, and long-lasting performance. Compatible with aluminum and other metal components found in EV cooling systems, ensuring reliable temperature control and extended system life.
        specifications:
          type: boolean
          example: false
        features_benefits:
          type: string
          example: Specially formulated for electric and hybrid vehicle cooling systems\nProvides excellent heat transfer and thermal stability\nPhosphate- and silicate-free formula to reduce deposits and corrosion\nOffers long-lasting protection for aluminum and metal components\nMaintains optimal battery and motor temperatures\nCompatible with a wide range of EVs and hybrid vehicles\nReady to use – no dilution required\nSize: 3.78 Liters
        note:
          type: boolean
          example: false
        how_to_use:
          type: string
          example: Make sure the vehicle is completely cool before opening the coolant reservoir.\nDrain any old coolant from the system if replacing.\nShake the bottle well before use.\nPour the coolant directly into the vehicle’s coolant reservoir or radiator.\nFill to the recommended level as per the vehicle manufacturer's instructions.\nStart the vehicle and run the cooling system to circulate the coolant.\nRecheck the level and top up if needed.\n\nNote: This product is pre-mixed and ready to use – do not dilute with water.\n
        active:
          type: boolean
          example: true
        description:
          type: boolean
          example: false
        description_sale:
          type: boolean
          example: false
        categories:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 702
              name:
                type: string
                example: Chemicals
              sequence:
                type: integer
                example: 10004
              parent_id:
                type: boolean
                example: false
        subcategories:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 711
              name:
                type: string
                example: Peak
              sequence:
                type: integer
                example: 10252
              parent_id:
                type: object
                properties:
                  id:
                    type: integer
                    example: 704
                  name:
                    type: string
                    example: Chemicals / Antifreeze
